<?php /* @var $this Hampe_Angular_Block_Constants */ ?>
<script type="text/javascript">
    (function(){
        'use strict';
        angular
            .module('mage.url')
            .constant('baseUrl','<?php echo $this->getBaseUrl(); ?>')
            .constant('skinUrl','<?php echo $this->getBaseSkinUrl(); ?>')
            .constant('mediaUrl','<?php echo $this->getBaseMediaUrl(); ?>')
            .constant('jsUrl','<?php echo $this->getBaseJsUrl(); ?>')
            .constant('baseUrlSecure','<?php echo $this->getBaseUrl(true); ?>')
            .constant('skinUrlSecure','<?php echo $this->getBaseSkinUrl(true); ?>')
            .constant('mediaUrlSecure','<?php echo $this->getBaseMediaUrl(true); ?>')
            .constant('jsUrlSecure','<?php echo $this->getBaseJsUrl(true); ?>')
        ;

        angular
            .module('mage.customer')
            .constant('customerLoggedIn', <?php echo $this->isCustomerLoggedIn(); ?>)
        ;

        angular
            .module('mage.price')
            .constant('priceFormat', <?php echo $this->getPriceFormat();?>);

        angular
            .module('mage.session')
            .constant('authToken', '<?php echo $this->getAuthToken();?>');
    })();
</script>